name: Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node
        uses: actions/setup-node@v4.1.0
        with:
          node-version: 17

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4.3.0
        with:
          dotnet-version: 6.0.x
